spring:
#  profiles:
#    active: dev
  application:
    name: identity-service
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://167.172.78.79:8888


code-advisors:
  ip: 202.178.125.77
  port: 9090
